name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13
    - name: Build automated tests
      run: dotnet build UserSecrets/UserSecrets.Tests/UserSecrets.Tests.csproj --configuration Release
    - name: Create empty file to get around error in .NET 6
      run: |
        #Create the secrets.json file
        New-Item UserSecrets\UserSecrets.Tests\secrets.json
        #Insert in empty braces to make it a valid (empty) json file
        "{}" | Set-Content UserSecrets\UserSecrets.Tests\secrets.json
        #Copy the secrets.json file to the bin directory, so that it will be present for the tests 
        xcopy "${{ github.workspace }}\UserSecrets\UserSecrets.Tests\secrets.json" "${{ github.workspace }}\UserSecrets\UserSecrets.Tests\bin\release\net6.0\"  /f /y
      shell: powershell
    - name: Run automated unit and integration tests
      run: dotnet test UserSecrets/UserSecrets.Tests/UserSecrets.Tests.csproj --configuration Release

