name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.1.21103.13
    - name: Run automated unit and integration tests
      run: dotnet test UserSecrets/UserSecrets.Tests/UserSecrets.Tests.csproj --configuration Release

